from pydantic import BaseModel
from typing import List, Optional

class JobCreate(BaseModel):
    title: str
    description: str
    experience_level: str
    recruiter_id: int
    # We don't ask for questions here; they are extracted from the PDF separately

class QuizResponse(BaseModel):
    questions: List[dict] # The list of MCQs generated by Gemini

class CodeSubmission(BaseModel):
    code: str
    language: str = "python"
    problem_id: int # Or just use job_id for simplicity in minor project