from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from app.core.database import engine, Base

# Import ALL models once (avoid duplicate table registration)
import app.models

# Import Routers
from app.routers import hr_agent, candidate_flow, auth

# Initialize the API
app = FastAPI(
    title="HireLens AI Agent",
    description="Backend for the Autonomous Recruitment Agent",
    version="2.0"
)

# Configure CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Create database tables ONCE at startup
Base.metadata.create_all(bind=engine)

# Include routers
app.include_router(auth.router)
app.include_router(hr_agent.router)
app.include_router(candidate_flow.router)

@app.get("/")
def home():
    return {
        "status": "online",
        "message": "HireLens AI Agent is running 🤖. Ready to process applications."
    }

# Context: Project "HireLens" - The Autonomous AI Recruiter
# I am building HireLens, an AI Agent designed to automate 90% of the recruitment process (Screening, L1, and L2 rounds). It acts as a complete "HR Replacement" for initial hiring stages.

# The Workflow (The 5 Gates): The system is a linear pipeline. A candidate must pass "Gate 1" to unlock "Gate 2", and so on.

# Phase 0 (HR Setup): HR uploads a Job Description + a PDF "Knowledge Base". The AI extracts questions from this PDF.

# Gate 1 (Proctored Quiz): The candidate takes an MCQ quiz generated by Gemini from the PDF.
# Constraint: Browser tab-switching is detected (Anti-Cheating).

# Gate 2 (AI Coding Round): A split-screen code editor (Monaco Editor).
# Constraint: The user's code is sent to Gemini (acting as a Compiler) to check for Logic + Time Complexity.

# Gate 3 (Technical Interview): An AI Avatar conducts a voice/chat interview.
# Logic: Deep technical questions based on the role.

# Gate 4 (HR Interview): The same Avatar switches persona to "Friendly HR" to assess culture fit.

# Gate 5 (Profile Scoring): The AI analyzes the Resume vs. Job Description vs. LinkedIn Profile to give a final "Trust Score".

# Tech Stack:
# Backend: Python (FastAPI), SQLite, Google Gemini API (for all AI logic).
# Frontend: React (Vite), Tailwind CSS, Framer Motion (Animations), Monaco Editor (Coding).

# Current File Structure: We have completed the Backend. It uses a Service-Repository Pattern.

# backend/
# ├── app/
# │   ├── __init__.py
# │   ├── main.py                 # 🚀 Entry Point (Initializes the Agent)
# │   │
# │   ├── core/                   # ⚙️ Configuration
# │   │   ├── __init__.py
# │   │   ├── config.py           # Loads .env (Gemini Key, DB URL)
# │   │   └── database.py         # DB Connection Session
# │   │
# │   ├── models/                 # 🗄️ Database Tables (The Memory)
# │   │   ├── __init__.py
# │   │   ├── users.py            # User & Role (HR/Candidate)
# │   │   ├── jobs.py             # Job Postings & Question Bank Links
# │   │   ├── assessments.py      # Stores ScoreCards (Gate 1-5 results)
# │   │   └── questions.py        # The extracted Questions Bank
# │   │
# │   ├── schemas/                # 📝 Data Validation (Pydantic)
# │   │   ├── __init__.py
# │   │   ├── auth_schemas.py     # Login/Register inputs
# │   │   ├── job_schemas.py      # Job Creation inputs
# │   │   └── interview_schemas.py # Chat & Answer inputs
# │   │
# │   ├── routers/                # 🚦 API Endpoints (The Nervous System)
# │   │   ├── __init__.py
# │   │   ├── auth.py             # Login/Register
# │   │   ├── hr_agent.py         # HR Actions (Upload PDF, Post Job)
# │   │   └── candidate_flow.py   # The 5-Gate Workflow APIs
# │   │
# │   └── services/               # 🤖 THE AI AGENTS (Logic Layers)
# │       ├── __init__.py
# │       ├── pdf_parser.py       # (Phase 0) Extracts text from HR PDFs
# │       ├── quiz_engine.py      # (Gate 1) Generates/Grades MCQs
# │       ├── code_compiler.py    # (Gate 2) AI-based Code Execution
# │       ├── interview_bot.py    # (Gate 3 & 4) The Visual Interviewer Logic
# │       └── profile_scorer.py   # (Gate 5) Cross-checks LinkedIn vs Resume
# │
# ├── uploads/                    # 📂 Temp storage for PDFs
# │   └── .gitkeep
# ├── requirements.txt            # Python Dependencies
# └── .env                        # 🔑 Secrets (API Keys)
# 
# frontend/src/
# ├── assets/                     # Images (Logo, Avatar Placeholder)
# │
# ├── components/                 # 🧩 Reusable UI Blocks
# │   ├── Layout/
# │   │   ├── Navbar.jsx          # Glassmorphism Header
# │   │   └── Sidebar.jsx         # For Dashboard navigation
# │   ├── Shared/
# │   │   ├── ProtectedRoute.jsx  # Security Wrapper (Redirects if not logged in)
# │   │   └── Loader.jsx          # AI "Thinking" Animation
# │   ├── Interview/
# │   │   ├── CodeEditor.jsx      # (Gate 2) Monaco Editor Wrapper
# │   │   ├── AudioVisualizer.jsx # (Gate 3) Animated Voice Waves
# │   │   └── Avatar3D.jsx        # (Gate 3) The Visual Agent
# │
# ├── pages/                      # 📄 Full Screens
# │   ├── Landing.jsx             # Hero Page
# │   ├── Auth/
# │   │   ├── Login.jsx
# │   │   └── Register.jsx
# │   ├── HR/
# │   │   ├── Dashboard.jsx       # View Applicants
# │   │   └── CreateJob.jsx       # Upload PDF & Setup Agent
# │   ├── Candidate/
# │   │   ├── JobBoard.jsx        # List of Open Roles
# │   │   ├── Gate1_Quiz.jsx      # Proctoring + MCQ Interface
# │   │   ├── Gate2_Coding.jsx    # Split Screen (Problem Left / Code Right)
# │   │   ├── Gate3_Interview.jsx # Camera + Mic Interface
# │   │   └── Result.jsx          # Final Scorecard
# │
# ├── context/                    # 🧠 State Management
# │   └── AuthContext.jsx         # Stores User Session
# │
# ├── services/                   # 🔌 API Connections
# │   └── api.js                  # Central Axios File
# │
# ├── App.jsx                     # Routing Logic
# ├── main.jsx                    # React Entry Point
# └── index.css                   # Tailwind Global Styles

# My Goal: I have finished the Backend code. I now need help to connecting each backend correctly with running it perfectly
